# Parameters for English version

author: Henry Fung
subtitle: Tech blog
description: Stay healthy & keep coding
keywords: Hugo,NexT,Theme,easily,powerful

linksSets:
  icon: fa fa-globe
  title: Friends

footer:
  since: 2022
  # 年份和版权信息之间的图标
  # Icon between year and copyright info.
  icon:
    # 图标名称
    # Icon name in Font Awesome.
    name: fa fa-heart
    # 开启图标动画效果
    # If you want to animate the icon, set it to true.
    animated: true
    # 使用16进制设置图标的颜色
    # Change the color of icon, using Hex Code.
    color: "#ff0000"
  vendors:
    enable: false
    title: Offering CDN & Cloud Resource

postFooter:
  endLineTip: ""

rewardSets:
  comment: '<i class="fa-solid fa-mug-hot"></i>Buy me a coffe ヾ(^▽^*)))'

githubBanner:
  # 是否开启显示
  # If true, will display banner.
  enable: true
  # 你的 Github 仓库地址
  # Your repository url on Github.
  permalink: https://github.com/henryfung3a27
  # 关注说明
  # Show this title when cursor move on.
  title: My Github

# waline:
#   enable: true
#   pageView: true
#   emoji: false
#   imgUploader: false
#   wordLimit: 200
#   requiredMeta: ["nick", "mail"]
#   serverURL: "#{Waline_Server_URL}"
#   placeholder: "Please leave your E-mail make me connect with you."

# Utterances 评论插件
# 更多配置信息请参考：https://utteranc.es
# Utterances comments system
# For more information: https://utteranc.es
utterances:
  enable: true
  # Github 仓库地址，格式：用户名/仓库名称
  # Github repository owner and name
  repo: username/repo-name
  # 问题标题的模式，可选值：pathname | url | title | og:title
  # Available values: pathname | url | title | og:title
  issueTerm: pathname
  # 问题的标签分类
  # Label flag for Github issues
  label: comments
  # 主题可选值： github-light | github-dark | preferred-color-scheme | github-dark-orange | icy-dark | dark-blue | photon-dark | boxy-light
  # Available values: github-light | github-dark | preferred-color-scheme | github-dark-orange | icy-dark | dark-blue | photon-dark | boxy-light
  theme: preferred-color-scheme
