main:
  - identifier: home
    name: Home
    pageref: /
    pre: home
    weight: 1
  - identifier: about
    name: About
    pageref: /about.html
    pre: user
    weight: 2
  # - identifier: democrat
  #   name: Demo
  #   pageref: /demo
  #   pre: fa-democrat
  #   weight: 3
  - identifier: posts
    name: Posts
    pageref: /posts
    pre: archive
    weight: 3
  # - identifier: archives
  #   name: Archives
  #   pageref: /archives
  #   pre: archive
  #   weight: 4
  # - identifier: commonweal
  #   name: Commonweal 404
  #   url: /404.html
  #   pre: heartbeat
  #   weight: 5
