main:
  - identifier: home
    name: 首页
    pageref: /
    pre: home
    weight: 1
  - identifier: about
    name: 关于
    pageref: /about.html
    pre: user
    weight: 2
  - identifier: democrat
    name: 示例
    pageref: /demo
    pre: democrat
    weight: 3
  - identifier: archives
    name: 归档
    pageref: /archives
    pre: archive
    weight: 4
  # - identifier: commonweal
  #   name: 公益 404
  #   url: /404.html
  #   pre: heartbeat
  #   weight: 5
